/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EelRouteImport } from './routes/eel'
import { Route as KilnRouteImport } from './routes/kiln'
import { Route as MeshlineRouteImport } from './routes/meshline'
import { Route as SlipRouteImport } from './routes/slip'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EelRoute = EelRouteImport.update({
  id: '/eel',
  path: '/eel',
  getParentRoute: () => rootRouteImport,
} as any)
const KilnRoute = KilnRouteImport.update({
  id: '/kiln',
  path: '/kiln',
  getParentRoute: () => rootRouteImport,
} as any)
const MeshlineRoute = MeshlineRouteImport.update({
  id: '/meshline',
  path: '/meshline',
  getParentRoute: () => rootRouteImport,
} as any)
const SlipRoute = SlipRouteImport.update({
  id: '/slip',
  path: '/slip',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/eel': typeof EelRoute
  '/kiln': typeof KilnRoute
  '/meshline': typeof MeshlineRoute
  '/slip': typeof SlipRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/eel': typeof EelRoute
  '/kiln': typeof KilnRoute
  '/meshline': typeof MeshlineRoute
  '/slip': typeof SlipRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/eel': typeof EelRoute
  '/kiln': typeof KilnRoute
  '/meshline': typeof MeshlineRoute
  '/slip': typeof SlipRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/eel' | '/kiln' | '/meshline' | '/slip'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/eel' | '/kiln' | '/meshline' | '/slip'
  id: '__root__' | '/' | '/eel' | '/kiln' | '/meshline' | '/slip'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EelRoute: typeof EelRoute
  KilnRoute: typeof KilnRoute
  MeshlineRoute: typeof MeshlineRoute
  SlipRoute: typeof SlipRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eel': {
      id: '/eel'
      path: '/eel'
      fullPath: '/eel'
      preLoaderRoute: typeof EelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kiln': {
      id: '/kiln'
      path: '/kiln'
      fullPath: '/kiln'
      preLoaderRoute: typeof KilnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meshline': {
      id: '/meshline'
      path: '/meshline'
      fullPath: '/meshline'
      preLoaderRoute: typeof MeshlineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slip': {
      id: '/slip'
      path: '/slip'
      fullPath: '/slip'
      preLoaderRoute: typeof SlipRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EelRoute: EelRoute,
  KilnRoute: KilnRoute,
  MeshlineRoute: MeshlineRoute,
  SlipRoute: SlipRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
